### PR TITLE
Prettier update

### LINKED ISSUE #198: Use Prettier
[What is Prettier?](https://prettier.io/docs/en/index.html)
[Why Prettier?](https://prettier.io/docs/en/why-prettier.html)
😍

### PR DESCRIPTION
**Pull request by MarckK**
Resolves #198

### CODE REVIEW

**Comment by MarckK** [comment]
Coverage is reduced as the number of lines has increased with the formatting done by Prettier (ratio of tests per line is reduced, so more untested lines).

**Comment by tiffon** [comment]
What's the relationship between this PR and #200?

**Comment by MarckK** [comment]
Hi @tiffon, that's a good question. #200 pretty prints the repo (.js and .json files), updates eslint dependencies, and creates a format script. The final step to integrating Prettier into the project was to create a pre-commit hook.  This can be done quite easily using the husky package, but that is not compatible with node 0.10/0.12.  

So I thought I would write a bash script to create the pre-commit hook and created this seperate, neater PR duplicating the work on #200 up until trying to create the pre-commit hook with husky.  I haven't written the bash script yet. The [Prettier docs give a nice script](https://prettier.io/docs/en/precommit.html) to work off of; however, docs recommend putting in .git/hooks/pre-commit and 1) my .git/hooks/files are now filled with husky stuff as those files are not populated per branch but shared across the repo 2) the script in .git/hooks/pre-commit will run locally for me, but it's not shared in the repo  -- and the whole point of the pre-commit hook was to make it easy to contribute to the open source project.

One solution is just to ask people to run the format script before committing (I had just really wanted to automate that) and a script that runs Prettier as part of our continuous integration checks. Similar to [what the React team do](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html).

I'm still so annoyed I can't get husky to work with our CI and all the node versions we are supporting. So much so, that I keep working on it. Hence the two very similar PRs.

**Comment by MarckK** [comment]
I believe I've found a solution to using husky with our CI tests and all the node versions we support. :)

**Pull request closed without merging**
