### PR TITLE
Use callbacks in UDPSender and remoteReporter

### PR DESCRIPTION
**Pull request by MarckK**
Flushes spans properly to backend
Signed-off-by: Kara de la Marck <karadelamarck@gmail.com>

### CODE REVIEW

**Comment by MarckK** [comment]
This is just a start.
It is flushing spans correctly to backend for simple application. But all the reporters should be made to use callbacks. Tests need to be changed.
And, yes, issue #32.

**Comment by MarckK** [comment]
I can work on issue #32 here or in a separate PR.

**Comment by MarckK** [comment]
Shall I work on issue #32 here or in a separate PR?

**Comment by yurishkuro** [comment]
@MarckK any reason this is not based off #218? That contained the typing changes

**Pull request merged**
