### PR TITLE
- sockets fix

### PR DESCRIPTION
**Pull request by yrsh**
PR solves this issue:
https://github.com/jaegertracing/jaeger-client-node/issues/353

### CODE REVIEW

**Comment by yrsh** [comment]
@yurishkuro In fact, now sockets are just hanging in open state, and every next request opens new socket. please take a look at this issue https://github.com/jaegertracing/jaeger-client-node/issues/353, the issue is documented in details.

**Comment by esimons** [comment]
We're also seeing this issue. Each span sent over HTTP appears to leave a connection open, eventually (in our case) leading to ECONNRESET due to an Istio circuit breaking on max connections.

**Comment by Dadabhvai-Kashyap** [comment]
Why the socket not close does, its affect my application say that the pool connection have exceeded the limit server, I can connect not a new socket. Istio not do a connect to server, numbers of socket limit

**Comment by esimons** [comment]
Alternate implementation offered in #356

**Comment by isbalashov** [comment]
Is there any chance this PR could be merged eventually? This gives me lots of troubles now, had to fork library in order to continue using jaeger

**Comment by yurishkuro** [comment]
there's more discussion happening in #356, and that fix looks safer than this PR, so I am going to close this, please watch the other one.

**Pull request closed without merging**
