### PR TITLE
Use the ip and hostname tags if provided

### PR DESCRIPTION
**Pull request by ledor473**
## Which problem is this PR solving?
Fixes https://github.com/jaegertracing/jaeger-client-node/issues/335

## Short description of the changes
- Check if there's already a value before using the default logic

### CODE REVIEW

**Comment by ledor473** [comment]
Oops I miss-click on `close`...

But yeah the CI seems to be waiting for a password 🤔

**Comment by black-adder** [comment]
I think it's related to: https://github.com/jaegertracing/jaeger/pull/153. This fix would be to add a check for `"$TRAVIS_SECURE_ENV_VARS" == "true"` like we did before or a quick workaround is to use another branch `ticketmaster:master` -> `ticketmaster:jaeger-fix`

**Comment by ledor473** [comment]
@black-adder backporting the fix worked 👍

**Comment by black-adder** [comment]
awesome, thanks!

**Pull request merged**
