### PR TITLE
Expose constants for easy usage

### PR DESCRIPTION
**Pull request by eldadcohen1**
I Exposed constants for easy usage.
For tracer configuration you should supply sampler type, it's a defined constant in the library.

### CODE REVIEW

**Comment by yurishkuro** [comment]
I have a small concern with this change because it may expose some constants that ideally should be kept private to the module.

**Comment by tiffon** [comment]
I agree with @yurishkuro, there are a lot of inner workings in the constants exports. 

Maybe something like the following would suffice?

```js
export const samplerTypes = {
  CONST: SAMPLER_TYPE_CONST,
  PROBABILISTIC: SAMPLER_TYPE_PROBABILISTIC
  RATE_LIMITING: SAMPLER_TYPE_RATE_LIMITING,
  LOWER_BOUND: SAMPLER_TYPE_LOWER_BOUND,
  REMOTE: SAMPLER_TYPE_REMOTE,
};

// ...

  samplerTypes: require('...').samplerTypes,
```

**Comment by eldadcohen1** [comment]
OK I agree, I'll fix it.

**Comment by yurishkuro** [comment]
closing due to inactivity.

**Pull request closed without merging**
