### PR TITLE
Remove deprecated env variables (4.x release)

### LINKED ISSUE #321: Remove deprecated environment variables
## Requirement - what kind of business use case are you trying to solve?
Unify configuration with env variables

## Problem - what in Jaeger blocks you from solving the requirement?
Mismatching environment variable naming (#313)

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Bring the configuration with env variables according to jaeger [doc](https://www.jaegertracing.io/docs/1.8/client-features/) in the next major releas

List of env variables to remove:
- [x] `JAEGER_REPORTER_AGENT_PORT`
- [x] `JAEGER_REPORTER_AGENT_HOST`
- [x] `JAEGER_REPORTER_ENDPOINT`
- [x] `JAEGER_REPORTER_USER`
- [x] `JAEGER_REPORTER_PASSWORD`
- [x] `JAEGER_SAMPLER_HOST`
- [x] `JAEGER_SAMPLER_PORT`
- [x] `JAEGER_DISABLE`

### PR DESCRIPTION
**Pull request by yepninja**
Resolves #321

### CODE REVIEW

**Comment by yepninja** [comment]
Release #328

**Comment by black-adder** [comment]
Thanks for this! Let's put this on ice for a while until we can figure out what other breaking changes we can introduce given how precious a major release is.

**Comment by yurishkuro** [comment]
indeed.  In fact, I would suggest a different approach - we should merge another PR that clearly tags the deprecated constants somehow as "to be removed in 4.x". Then it will be a lot easier to remove them closer to 4.x than to keep this PR open and possibly do complicated merges.

**Comment by yurishkuro** [comment]
Very old PR, closing. Given that this SDK is not being actively evolved further, it's not so bad to continue supporting old names.

**Pull request closed without merging**
