### PR TITLE
Fix HTTP sender to work with TLS

### PR DESCRIPTION
**Pull request by keitwb**
The http.Agent instance doesn't work with HTTPS and requires a separate type of agent.

### CODE REVIEW

**Comment by keitwb** [comment]
Yes, I committed a self-signed cert/key pair to the repo that we can use to start up an TLS server.

**Comment by yurishkuro** [comment]
fails with 
```
1) http sender should handle HTTPS collectors:
     Error: ENOENT, no such file or directory '/home/travis/build/jaegertracing/jaeger-client-node/dist/test/server.key'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)
      at Context.<anonymous> (dist/test/http_sender.js:314:25)
```

Maybe consider just embedding the cert/key as string constants in the test file, as otherwise they need to be copied to dist, unnecessary churn.

**Comment by keitwb** [comment]
Hmm...I'm going to have to figure out something else for Node 0.10 to support HTTPS.

**Comment by yurishkuro** [comment]
> Hmm...I'm going to have to figure out something else for Node 0.10 to support HTTPS.

I think it's fine to have fewer features for 0.10 - throw explicit exception that HTTPS is not supported there and have a branched unit tests for that.

**Comment by yurishkuro** [comment]
also, if you do exclude 0.10 for https, please add a note in the readme

**Comment by keitwb** [comment]
@yurishkuro I was able to make it work by using the specific `https.request` method where appropriate.

**Comment by yurishkuro** [comment]
Thanks!

**Pull request merged**
