### PR TITLE
WIP: Eslint config is fixed

### LINKED ISSUE #133: Fix ESlint configuration and lint all files
The current ESLint configuration is broken, and doesn't seem to be enforced during builds.

### PR DESCRIPTION
**Pull request by yepninja**
Resolves #133

### CODE REVIEW

**Comment by yepninja** [comment]
@yurishkuro @black-adder 
Situation wit eslint is unclear. It doesn't work now at all. After the fix, it throws more than a thousand error. Indeed rules don't match to the written code.

**Comment by yepninja** [comment]
I'll try to generate config according to the written code. Maybe a minimal working config for the first time.

**Comment by yurishkuro** [comment]
thanks again for your help with this repo, much appreciated.

**Comment by yurishkuro** [comment]
No follow-up from the author, closing.

**Pull request closed without merging**
